[meta]
environment = "other"
project = "polynuxt"

[system]
phpVersion = "8.5"
mysqlVersion = "8.4"
nodeVersion = "24"
opensearchVersion = "3.5.0"
composerVersion = "2.10"

[workbench]
localDbName = "polynuxt"

[[workbench.shops]]
domain = "polynuxt"
is_default = true
